server:
  port: 8081 # Ensure this port matches the one configured in credit-application-service

spring:
  application:
    name: risk-central-mock-service

logging:
  level:
    root: INFO
    com.coopcredit: DEBUG
